// Regenerates src/prompts.ts for the plugin package from prompts/*.md.
// The generated module is self-contained (no runtime filesystem reads), so the
// plugin keeps working no matter how the host bundles or relocates plugin code.
//
//   node scripts/sync-prompts.mjs
//
// Source of truth (插件包内):
//   .opencode/plugins/oc-infinite-gen-4/prompts/infinite-gen-4.md        (Order 100 通用内核)
//   .opencode/plugins/oc-infinite-gen-4/prompts/infinite-gen-4.1-flash.md (Order 200 强化镜像)
//   .opencode/plugins/oc-infinite-gen-4/prompts/infinite-gen-3.md        (历史兼容文件名)

import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const pluginRoot = join(root, ".opencode", "plugins", "oc-infinite-gen-4")

const SOURCES = {
  core: "prompts/infinite-gen-4.md",
  reinforce: "prompts/infinite-gen-4.1-flash.md",
  legacy: "prompts/infinite-gen-3.md",
}

const text = {}
const hashes = {}
for (const [key, relative] of Object.entries(SOURCES)) {
  const value = readFileSync(join(pluginRoot, relative), "utf8")
  text[key] = value
  hashes[key] = createHash("sha256").update(value, "utf8").digest("hex")
}

const unique = new Set(Object.values(hashes))
const shared = unique.size === 1
if (!shared) {
  console.error("prompt sources diverge — refusing to generate")
  for (const [key, hash] of Object.entries(hashes)) console.error(`  ${SOURCES[key]}: ${hash}`)
  process.exit(1)
}

const output = `// AUTO-GENERATED by scripts/sync-prompts.mjs — do not edit by hand.
//
// 无限四代 (Infinite Generation Four) kernel payloads, inlined as string
// literals so the plugin has no runtime filesystem dependency. The markdown
// files under prompts/ remain the human-readable source of truth; run the
// sync script after editing them, then run scripts/verify.mjs.
//
// SHA256 (all three sources are byte-identical): ${hashes.core}

export const KERNEL_SHA256 = "${hashes.core}"

export const PROMPT_CORE = ${JSON.stringify(text.core)}

export const PROMPT_REINFORCE = ${JSON.stringify(text.reinforce)}

export const PROMPT_LEGACY = ${JSON.stringify(text.legacy)}

export interface KernelPrompts {
  /** Order 100 通用内核 (prompts/infinite-gen-4.md). */
  readonly core: string
  /** Order 200 强化镜像 (prompts/infinite-gen-4.1-flash.md), 与 core 逐字一致. */
  readonly reinforce: string
  /** 历史兼容文件名 (prompts/infinite-gen-3.md), 与 core 逐字一致. */
  readonly legacy: string
  /** Kernel payload SHA256, identical for all three sources. */
  readonly sha256: string
}

export function loadKernelPrompts(): KernelPrompts {
  return { core: PROMPT_CORE, reinforce: PROMPT_REINFORCE, legacy: PROMPT_LEGACY, sha256: KERNEL_SHA256 }
}
`

writeFileSync(join(pluginRoot, "src/prompts.ts"), output, "utf8")
console.log(`generated src/prompts.ts (sha256=${hashes.core}, bytes=${Buffer.byteLength(text.core)})`)
